### ISSUE TITLE
Starting Seed randomization?

### ISSUE THREAD

**Issue by Darkmega18** [AndreyMrovol/LethalWeatherTweaks#10]
Are you able to randomize the starting seed each time so that the weathers are never the same starting off? Cause I'm ensure if you set it directly through your config or if the setting of zero means you make one up?

It'd be nice if that randomness was there every time you reset/start a save so it's different. Rather than being stuck always going to the same place cause thats the seed of the weather always.

**Comment by AndreyMrovol** [comment]
Hey, thanks for the suggestion - the option will be added in next release.

**Comment by Darkmega18** [comment]
thanks plenty. :)

**Comment by juicyslew** [comment]
Not to put pressure, but still hoping for this.

**Comment by AndreyMrovol** [comment]
Hey, no worries - this will be added in the next version, sadly I don't have ETA yet

**Comment by AndreyMrovol** [comment]
@Darkmega18 @juicyslew 

Hey, as of WeatherTweaksBeta v0.20.8 the following options have been added:

- `FirstDaySpecial` (a toggle for current first-day algorithm)
- `FirstDayRandomSeed` (a toggle for randomizing the first day seed)


Please check it out and let me know if you encounter any issues 😄
