### ISSUE TITLE
Beta thunderstore page has the wrong tags

### ISSUE THREAD

**Issue by CatsArmy** [AndreyMrovol/LethalWeatherTweaks#15]
correct tags:
{
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/104517593/d4e2e6d5-ff17-4fe0-9e65-8a792c9997f7)
}

current beta tags:
{
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/104517593/e4dde25d-e8b7-4f6c-af27-a717239f6936)
{

**Comment by AndreyMrovol** [comment]
Hey, this is intentional - I didn't want the beta version to show up on my modpage (so people wouldn't download it *as their normal version*)

**Comment by AndreyMrovol** [comment]
I'm talking about this page: https://thunderstore.io/c/lethal-company/p/mrov/

**Comment by CatsArmy** [comment]
You can still add the other tags but also keep that tag just having it makes it not show up on the main page

**Comment by CatsArmy** [comment]
![Screenshot_20240324-161425.png](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/104517593/67c9db5e-64a3-4314-844c-4d79a4ea4969)

![Screenshot_20240324-161559.png](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/104517593/b1520618-1bcf-45ab-addd-42afe3e2ef75)


See what I mean now you can add the tags but also keep that one
