### ISSUE TITLE
Go to the company，The door won't open

### ISSUE THREAD

**Issue by 1410677474** [AndreyMrovol/LethalWeatherTweaks#16]

**Comment by AndreyMrovol** [comment]
Hey @1410677474, thanks for your report - could you provide more info?

Are you using the `Beta` version (and if yes, what version are you using)?
Can you send the .log?
Can you send the modpack code?

**Comment by 1410677474** [comment]
version:BETA  0.10.4
I'm pretty sure it's this module
You can try it. Start by going to the company

**Comment by AndreyMrovol** [comment]
I've got it fixed, I'll let you know when the update goes live - thanks for your report!

**Comment by AndreyMrovol** [comment]
Hey, the updated Beta version should be available to download from Thunderstore - please check it out!

**Comment by 1410677474** [comment]
I got fired.  The doors won't open  news version

**Comment by AndreyMrovol** [comment]
> I got fired. The doors won't open news version

I'll check it out

**Comment by AndreyMrovol** [comment]
I cannot reproduce the issue - can you send me your modpack code, @1410677474?

**Comment by 1410677474** [comment]
018e7b8a-1cbe-7ad7-c92f-6951acb6cacf

**Comment by 1410677474** [comment]
> I cannot reproduce the issue - can you send me your modpack code, @1410677474?

code：018e7b8a-1cbe-7ad7-c92f-6951acb6cacf

**Comment by 1410677474** [comment]
Sorry, it works fine
