### ISSUE TITLE
Weather Report on Modded Screens.

### ISSUE THREAD

**Issue by Cracky4589** [AndreyMrovol/LethalWeatherTweaks#19]
Hello, not a bug but more of a comptability issue but, with some modded screens like OpenMonitors. The weather report list the current weather correclty instead of UNKNOW or Uncertain. The issue can be fixed by turning off the weather report on the screen.

**Comment by AndreyMrovol** [comment]
Hey, thanks for your report - are you using the "beta" version of WeatherTweaks?

**Comment by Cracky4589** [comment]
Nope, the "stable" version!

**Comment by AndreyMrovol** [comment]
Alright, I'll look into it - thanks for your report!

**Comment by AndreyMrovol** [comment]
I'm gonna be honest - I didn't know about that mod existing. Have you tried using [GeneralImprovements](https://thunderstore.io/c/lethal-company/p/ShaosilGaming/GeneralImprovements/)? It has the same features as the one you've sent *and* it's fully compatible with WeatherTweaks

**Comment by AndreyMrovol** [comment]
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/32998721/577809c7-36bc-496c-92f4-252c30344ad0)
I managed to get it fixed, please check if the latest update on thunderstore resolves your issue 😄

**Comment by Cracky4589** [comment]
Thanks for the quick update!! Really cool!! And I didn't test with the monitors of GeneralImprovements honestly I didn't tought it gonna work but oh well! I only tested OpenMonitors or other variants. But OpenMonitors is the most recent screen mod I use. Thanks again!
