### ISSUE TITLE
True weather is still shown when routing to a moon

### ISSUE THREAD

**Issue by dragonmcmx1** [AndreyMrovol/LethalWeatherTweaks#2]
When selecting a moon to route to, the message prompting you to confirm your input still displays the moon's true weather despite UncertainWeather being enabled.

![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/155202666/67646af9-1596-4d8b-87dc-047e5035364d)
![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/155202666/9e8a90f6-66c4-4ad1-9d17-612f5ce3c74f)

**Comment by dragonmcmx1** [comment]
On another note, requesting compatibility with LethalExpansion and LethalExpansionCore if possible. With either mod enabled, the status monitor in the ship still shows unknown at times meaning the UncertainWeather feature is working to some extent, it's just not displaying on the terminal at all.

**Comment by AndreyMrovol** [comment]
> When selecting a moon to route to, the message prompting you to confirm your input still displays the moon's true weather despite UncertainWeather being enabled.
> 
> ![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/155202666/67646af9-1596-4d8b-87dc-047e5035364d)
> ![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/155202666/9e8a90f6-66c4-4ad1-9d17-612f5ce3c74f)
> 

Hi, thanks for your report - I know about this bug and it's gonna be fixed.

**Comment by AndreyMrovol** [comment]
> On another note, requesting compatibility with LethalExpansion and LethalExpansionCore if possible. With either mod enabled, the status monitor in the ship still shows unknown at times meaning the UncertainWeather feature is working to some extent, it's just not displaying on the terminal at all.

I'll look into it - good to know that LethalExtension modifies moons list

**Comment by AndreyMrovol** [comment]
Hey, i've pushed v0.1.2 - please check if it fixes your issue

**Comment by dragonmcmx1** [comment]
Looks like that fixed it. Thank you!
