### ISSUE TITLE
[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by CoolLKKPS** [AndreyMrovol/LethalWeatherTweaks#20]
[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element
Stack trace:
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0011)
WeatherTweaks.Variables.GetLevelWeatherVariable (LevelWeatherType weatherType, System.Boolean variable2) (at <2417152be7b841de9942a6e52483b834>:IL_0045)
(wrapper dynamic-method) FloodWeather.DMD<FloodWeather::OnEnable>(FloodWeather)
UnityEngine.GameObject:SetActive(GameObject, Boolean)
OopsAllFlooded.Patches.RoundPatch:FloodSpawnPatch()
StartOfRound:DMD<StartOfRound::OnShipLandedMiscEvents>(StartOfRound)
<openingDoorsSequence>d__248:DMD<StartOfRound+<openingDoorsSequence>d__248::MoveNext>(<openingDoorsSequence>d__248)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by CoolLKKPS** [comment]
@AndreyMrovol Conflict with `OopsAllFlooded` mod i think

**Comment by CoolLKKPS** [comment]
and beta latest version

**Comment by CoolLKKPS** [comment]
and this issue i found that may cause by vanilla, with solo, flood are always rised to maximum level at the beginning, that's bad if with `OopsAllFlooded` mod, and also i have to remind u, stomy weather
[LogOutput.log](https://github.com/AndreyMrovol/LethalWeatherTweaks/files/15245790/LogOutput.log)

**Comment by CoolLKKPS** [comment]
idk is that fix or not, but i will close it

**Comment by CoolLKKPS** [comment]
continue #23

**Comment by AndreyMrovol** [comment]
alrighty, I'll take a look at this
