### ISSUE TITLE
[Error  : Unity Log] NullReferenceException (beta version)

### ISSUE THREAD

**Issue by CoolLKKPS** [AndreyMrovol/LethalWeatherTweaks#23]
[Error  : Unity Log] NullReferenceException
Stack trace:
WeatherRegistry.ImprovedWeatherEffect.set_EffectEnabled (System.Boolean value) (at <a8789d3648a44aa89286a000a526f63d>:IL_002C)
WeatherRegistry.ImprovedWeatherEffect.DisableEffect (System.Boolean permament) (at <a8789d3648a44aa89286a000a526f63d>:IL_0007)
WeatherTweaks.GameInteraction.SetWeatherEffects (TimeOfDay timeOfDay, System.Collections.Generic.List`1[T] weatherEffects) (at <eb0cc75e9f7548d8aca138be8d63b656>:IL_014F)
WeatherTweaks.NetworkedConfig.WeatherEffectsReceived (System.String weatherEffects) (at <eb0cc75e9f7548d8aca138be8d63b656>:IL_00F2)
LethalNetworkAPI.LethalNetworkVariable`1[TData].set_Value (TData value) (at ./Variable/LethalNetworkVariable.cs:104)
WeatherTweaks.NetworkedConfig.SetWeatherEffects (System.Collections.Generic.List`1[T] weathers) (at <eb0cc75e9f7548d8aca138be8d63b656>:IL_00A1)
WeatherTweaks.OpeningDoorsSequencePatch.SetWeatherEffects () (at <eb0cc75e9f7548d8aca138be8d63b656>:IL_007D)
(wrapper dynamic-method) WeatherRegistry.OpeningDoorsSequencePatch.DMD<WeatherRegistry.OpeningDoorsSequencePatch::SetWeatherEffects>()
(wrapper dynamic-method) StartOfRound+<openingDoorsSequence>d__248.DMD<StartOfRound+<openingDoorsSequence>d__248::MoveNext>(StartOfRound/<openingDoorsSequence>d__248)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by CoolLKKPS** [comment]
@AndreyMrovol

**Comment by CoolLKKPS** [comment]
[LogOutput.txt](https://github.com/user-attachments/files/15752700/LogOutput.txt)

**Comment by CoolLKKPS** [comment]
ok i will roll back to 1.14.11, even have those error

[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element
Stack trace:
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0011)
WeatherTweaks.Variables.GetLevelWeatherVariable (LevelWeatherType weatherType, System.Boolean variable2) (at <1669d189bc794b3f8a76f9e835c41fbc>:IL_0045)
(wrapper dynamic-method) FloodWeather.DMD<FloodWeather::OnEnable>(FloodWeather)
UnityEngine.GameObject:SetActive(GameObject, Boolean)
OopsAllFlooded.Patches.RoundPatch:FloodSpawnPatch()
StartOfRound:DMD<StartOfRound::OnShipLandedMiscEvents>(StartOfRound)
<openingDoorsSequence>d__248:DMD<StartOfRound+<openingDoorsSequence>d__248::MoveNext>(<openingDoorsSequence>d__248)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by AndreyMrovol** [comment]
Hey, I've uploaded new versions of weather registry and weathertweaks, please let me know if it fixes your issue

**Comment by CoolLKKPS** [comment]
@AndreyMrovol uh nothing change?
[Error  : Unity Log] NullReferenceException
Stack trace:
WeatherRegistry.ImprovedWeatherEffect.set_EffectEnabled (System.Boolean value) (at <5b5aeb57b4bd459f8986fb1cf11a544b>:IL_002C)
WeatherRegistry.ImprovedWeatherEffect.DisableEffect (System.Boolean permament) (at <5b5aeb57b4bd459f8986fb1cf11a544b>:IL_0007)
WeatherTweaks.GameInteraction.SetWeatherEffects (TimeOfDay timeOfDay, System.Collections.Generic.List`1[T] weatherEffects) (at <2417152be7b841de9942a6e52483b834>:IL_014F)
WeatherTweaks.NetworkedConfig.WeatherEffectsReceived (System.String weatherEffects) (at <2417152be7b841de9942a6e52483b834>:IL_00F2)
LethalNetworkAPI.LethalNetworkVariable`1[TData].set_Value (TData value) (at ./Variable/LethalNetworkVariable.cs:104)
WeatherTweaks.NetworkedConfig.SetWeatherEffects (System.Collections.Generic.List`1[T] weathers) (at <2417152be7b841de9942a6e52483b834>:IL_00C7)
WeatherTweaks.OpeningDoorsSequencePatch.SetWeatherEffects () (at <2417152be7b841de9942a6e52483b834>:IL_007D)
(wrapper dynamic-method) WeatherRegistry.OpeningDoorsSequencePatch.DMD<WeatherRegistry.OpeningDoorsSequencePatch::SetWeatherEffects>()
(wrapper dynamic-method) StartOfRound+<openingDoorsSequence>d__248.DMD<StartOfRound+<openingDoorsSequence>d__248::MoveNext>(StartOfRound/<openingDoorsSequence>d__248)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by CoolLKKPS** [comment]
maybe u need my modpack? bc now 3 different error log directly showing this mod has compatibility`?` issues

**Comment by AndreyMrovol** [comment]
I've managed to find the issue, I'll push the fix shortly

**Comment by CoolLKKPS** [comment]
so for me, to reproduce just pull the lever to start the game, once enter the game u can just quit to main menu and re-create a lobby, then start the game again, and after that the ship door should be won't automatically open and the day of time in the game won't functional

**Comment by AndreyMrovol** [comment]
I've uploaded a fix (v. 0.20.3) - please let me know if it fixes your issue!

**Comment by CoolLKKPS** [comment]
@AndreyMrovol ok this issue fixed, but can u investigate why i still can get this error?
[Error  : Unity Log] InvalidOperationException: Sequence contains no matching element
Stack trace:
System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0011)
WeatherTweaks.Variables.GetLevelWeatherVariable (LevelWeatherType weatherType, System.Boolean variable2) (at <2417152be7b841de9942a6e52483b834>:IL_0045)
(wrapper dynamic-method) FloodWeather.DMD<FloodWeather::OnEnable>(FloodWeather)
UnityEngine.GameObject:SetActive(GameObject, Boolean)
OopsAllFlooded.Patches.RoundPatch:FloodSpawnPatch()
StartOfRound:DMD<StartOfRound::OnShipLandedMiscEvents>(StartOfRound)
<openingDoorsSequence>d__248:DMD<StartOfRound+<openingDoorsSequence>d__248::MoveNext>(<openingDoorsSequence>d__248)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by AndreyMrovol** [comment]
> @AndreyMrovol ok this issue fixed, but can u investigate why i still can get this error? [Error : Unity Log] InvalidOperationException: Sequence contains no matching element Stack trace: System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at :IL_0011) WeatherTweaks.Variables.GetLevelWeatherVariable (LevelWeatherType weatherType, System.Boolean variable2) (at <2417152be7b841de9942a6e52483b834>:IL_0045) (wrapper dynamic-method) FloodWeather.DMDFloodWeather::OnEnable(FloodWeather) UnityEngine.GameObject:SetActive(GameObject, Boolean) OopsAllFlooded.Patches.RoundPatch:FloodSpawnPatch() StartOfRound:DMDStartOfRound::OnShipLandedMiscEvents(StartOfRound) d__248:DMD<StartOfRound+d__248::MoveNext>(d__248) UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

oh, was that not fixed by my previous patch? it should *only* show up when the current weather is not in randomWeathers of the level (something i've fixed)

**Comment by CoolLKKPS** [comment]
uh but i got this error, when in stomy weather, monitor are display `foggy?`
it should be not random weather i think
