### ISSUE TITLE
Can't re-host after leaving an existing lobby

### ISSUE THREAD

**Issue by Bluerith** [AndreyMrovol/LethalWeatherTweaks#26]
I really like this mod but it does not seem to allow me to host a second lobby after leaving the first one within a playing session. I have to restart the game in order to make a new lobby, which is a tad inconvenient. 

This issue is apparent on the Beta version, I believe the stable release is fine!

**Comment by AndreyMrovol** [comment]
Hey, sorry for that - it's connected to LethalNetworkAPI's v3.0.0 update, I'll get it fixed ASAP.

**Comment by AndreyMrovol** [comment]
Hey, i've pushed the update to Thunderstore - please check it out and let me know if the issue is fixed 😅
