### ISSUE TITLE
No config option for "no weather conditions shown"

### ISSUE THREAD

**Issue by TheDebbyCase** [AndreyMrovol/LethalWeatherTweaks#3]
![image_2024-02-04_205434013](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/136064782/647998d7-83a9-4e50-9115-96605adb2e6b)
If I'm missing something I do apologise, but I'm unable to find a way to completely hide the weather conditions. I'm not sure if this is supposed to be a config option or something else. The config options above are all that I see bar the settings for each specific weather condition. I feel like there should be more? (Most recent update) Thanks

**Comment by TheDebbyCase** [comment]
Don't mind the false settings on the first two options, I was just testing to see if anything obvious was broken, the issue applies with them both set to true

**Comment by AndreyMrovol** [comment]
Hey, if I understand your question correctly, `AlwaysUncertain` should hide all *true* conditions

**Comment by TheDebbyCase** [comment]
So is there no way to hide the weather conditions altogether? "no weather conditions shown" to me implies that both true and false conditions shouldn't be shown, am I misunderstanding something?

**Comment by AndreyMrovol** [comment]
Oh, so you want every planet's weather to be `[UNKNOWN]`?

**Comment by TheDebbyCase** [comment]
Yes, if that's not actually possible it's okay, I'm now just really confused as to what the README means by "(optional) no weather conditions shown mode"

**Comment by AndreyMrovol** [comment]
Okay, I see what you meant - I will add an option for all unknown weathers (instead of just uncertain) and let you know.



> Yes, if that's not actually possible it's okay, I'm now just really confused as to what the README means by "(optional) no weather conditions shown mode"

What I meant by that was no **actual** weather conditions (oopsie).

**Comment by TheDebbyCase** [comment]
Ahh I see, that makes sense. I understand you haven't yet gotten to documentation so it makes sense some stuff is unclear. I really like the weighted weather but I do prefer just not being told what weather I'm getting into. It could probably be achievable with this and the HiddenWeather mod, but I haven't tried it and it could cause compatibility issues, but if you're willing to add it as a feature that would be excellent. I suppose this issue can be closed?

**Comment by AndreyMrovol** [comment]
I'm gonna close this when the feature is gonna be added (and confirmed working :D)

**Comment by TheDebbyCase** [comment]
Alright sounds good, I'll be first to test once you let me know

**Comment by AndreyMrovol** [comment]
I've just pushed v0.2.0 to Thunderstore - please let me know how it works!

**Comment by TheDebbyCase** [comment]
Hi, you caught me as I was getting to sleep but I've just got done testing it. Works perfectly with expected configuration, "AlwaysUncertain: true", "AlwaysUnknown: true". While AlwaysUnknown is true the other Uncertain condition configs have no impact which is great. Only thing I've noticed is that if MapScreenPatch is false then the terminal displays vanilla weather, though I don't know if that's intended on your part. (Though turning off MapScreenPatch also gives away the weather anyway so it wouldn't make sense to have it be false.) Otherwise, works perfectly!

**Comment by AndreyMrovol** [comment]
Hey, I'm patching `SetMapScreenInfoToCurrentLevel` (the ship's main screen) and `TextPostProcess` (terminal displaying moon list) to prevent game from displaying *actual* weather types - if one of those is disabled, you could easily check the *true* weather, so as a prevention i've tied them both to disabling the uncertain weather mechanic completely.



> Works perfectly with expected configuration, "AlwaysUncertain: true", "AlwaysUnknown: true". While AlwaysUnknown is true the other Uncertain condition configs have no impact which is great. 

>Otherwise, works perfectly!

That's great to hear! :D
