### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Tbird2005** [AndreyMrovol/LethalWeatherTweaks#31]
Theres this mod that makes it so moons have their own time cycles, so you can land on a moon late or early in the day, and the only way to tell the moons time is by looking on the monitor or in the terminal, and your mod is being fucky wucky with the monitor and terminal and making the time value never appear, so i cant tell what time it is on a moon. Please fix this incompatibility.

Mod in question: https://thunderstore.io/c/lethal-company/p/Swaggies/VersionNine/

**Comment by AndreyMrovol** [comment]
Hey, right now I'm not planning to include compatibility with that mod.
