### ISSUE TITLE
Default config makes weather always bad

### ISSUE THREAD

**Issue by Hardeh** [AndreyMrovol/LethalWeatherTweaks#4]
We played for 4 hours and had clear weather only once, on first experiment. All other times weather was bad. Is that normal?

**Comment by AndreyMrovol** [comment]
Hey, thanks for creating the issue - I've messed up the multipliers calculation and `None` weather has a maximum weight of 1 - I'm gonna fix that today.

In the meantime you can set `GameLengthMultiplier` and `GamePlayersMultiplier` to 0 to disable this calculation altogether.

I'm really sorry for that.

**Comment by Hardeh** [comment]
That's no problem, glad to see it fixed

**Comment by AndreyMrovol** [comment]
Hey, i've just pushed v0.3.0 - please re-generate the config file and let me know if this fixes the issue.

**Comment by Hardeh** [comment]
Seems like it's fixed, although i have to test with friends in multiplayer too
