### ISSUE TITLE
Error, Need Update LLL 

### ISSUE THREAD

**Issue by DHStyle541** [AndreyMrovol/LethalWeatherTweaks#6]
Hi, This is mods need update to new Version LLL tq
Maybe? because LLL version v1.1.3

![image](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/154591650/82d10e8b-6d68-45f4-a245-ebfa077a2956)

**Comment by Hardeh** [comment]
Yes, looks like mod is not compatible to the latest LLL update. Terminal patch doesn't work, weather is not shown on ship moon information screen as well.

**Comment by AndreyMrovol** [comment]
Hey, when LLL's latest version will be stable and without major bugs, I'll update the dependency.

**Comment by AndreyMrovol** [comment]
This mod will not work on latest LLL

**Comment by DHStyle541** [comment]
maybe you need recode because new LLL?

**Comment by AndreyMrovol** [comment]
I've pushed v0.4.2 to Thunderstore, which works with LethalLevelLoader v1.1.0+
