### ISSUE TITLE
Weather change

### ISSUE THREAD

**Issue by JochenYang** [AndreyMrovol/LethalWeatherTweaks#7]
Can this module be switched randomly within a game?

**Comment by AndreyMrovol** [comment]
Hey, sorry for the late reply - what do you mean? 
What are you trying to achieve?

**Comment by JochenYang** [comment]
The effect I want to achieve is that after the start of a game, the weather can be randomly changed from sunny to other different weather effects, such as the morning sun, the afternoon may become rainy.I don't know whether it can be realized, thank you for your reply!

**Comment by AndreyMrovol** [comment]
I'm working on it.

**Comment by JochenYang** [comment]
thanks，bro

**Comment by AndreyMrovol** [comment]
Hey @JochenYang, I've pushed beta version 0.8.0 to Thunderstore - https://thunderstore.io/c/lethal-company/p/mrov/BetaWeatherTweaksBeta/ which adds `progressing weather` type - please check it out and let me know about any issues that you encounter
