### ISSUE TITLE
Modded Moon Compat

### ISSUE THREAD

**Issue by TheChristinson** [AndreyMrovol/LethalWeatherTweaks#9]
Using the setting to make weather always unknown doesn't work properly with modded moons via LECore. Everything works as intended, except when you attempt to route to the moon, on the "Confirm or Deny" page, it still lists the moons weather. This only happens for the custom moons, though
Example:
![Lethal Company 2024-03-04 15-45-14](https://github.com/AndreyMrovol/LethalWeatherTweaks/assets/42426439/a9a6147b-bf76-49cf-b4b6-0cc1738fc999)

**Comment by AndreyMrovol** [comment]
Hey, thanks for your report! I thought I already covered that in my terminal patch (https://github.com/AndreyMrovol/LethalWeatherTweaks/blob/main/WeatherTweaks%2FPatches%2FTextPostProcess.cs#L19-L30), but I guess LEcore does it differently - I'll check it out in detail.
